[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
auto_detect_remappings = false

[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
